os:
- linux
env:
  matrix:
  - LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/
  global:
    secure: yy5mARZqymFCFBMgZioUDIiDBitpBEjT+uCUgBBdGQ8muHma167xhgCYu9thzb/dJRPgT4aEb9jIhWS9dNnNCnIkuDGlwGmQN0ExHM2S+D3brPY3rTWPeqj3y7c/57sbPcQeCtT8cWhK5W+raCHjvIAf4z0JxvYfu32vry5bZMU=
install:
- curl https://static.rust-lang.org/rustup.sh | sudo sh
script:
- cargo build --verbose
- cargo test --verbose
- cargo doc
after_success: 'curl https://raw.githubusercontent.com/iron-bot/build-doc/master/build-doc.sh
  | sh '
